name: Testing and Merging Branch to main
on: workflow_dispatch
jobs:
  FrontEndTesting-job:
    runs-on: ubuntu-latest
    steps:
      - name: downloading repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd basic-testing-frontend
          npm install
      - name: initating the testing
        run: |
          cd basic-testing-frontend
          npm test
  BackEndTesting-job:
    runs-on: ubuntu-latest
    steps:
      - name: downloading repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip3 install pytest
      - name: initating the testing
        run: |
          cd test
          pytest test_*.py
  EndToEndTesting-job: 
    runs-on: ubuntu-latest
    steps:
      - name: downloading repo
        uses: actions/checkout@v3
      - name: cypress
        uses: cypress-io/github-action@v5.0.0
        with:
          browser: chrome
          headless: true
